### PR TITLE
Feature/75 beautify

### PR DESCRIPTION
**Pull request by KirschbaumP**

### CODE REVIEW

**Comment by abush3** [comment]
Check the create question feature on the lecture view

**Review by CevG33ko — DISMISSED** [review]
nice

**Comment by KirschbaumP** [comment]
> Check the create question feature on the lecture view

Fixed.

**Comment by abush3** [comment]
The create question feature overflows on the emulator that I am using. Make sure that the feature works for all devices.

**Comment by KirschbaumP** [comment]
There are some strange things. I can show you tomorrow the bugs

**Comment by KirschbaumP** [comment]
Maybe we merge this and create a bugfix ticket to get the feature in this sprint.

**Review by CevG33ko — APPROVED** [review]
great

**Pull request merged**
